#
# This file contains configuration flags for the site
#

# Site name
name: Mike's Site

# Site description
description: Interaction Designer in Chicago

# URL of avatar image
avatar: https://avatars3.githubusercontent.com/u/319534?v=3&s=460

# Markdown parser
markdown: redcarpet

# Enable typographic quotes and dashes
redcarpet:
    extensions: ['smart']

# Syntax highlighting engine
highlighter: pygments

# Permalink format
permalink: /:title/

# Path to site images; when called, include trailing slash
# e.g., {{site.img}}/folder/image.png
img: /web/images

# Exclude these files from production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - Guardfile
    - Rakefile
    - LICENSE
    - README.md
